// <auto-generated />
namespace MacroTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _02_24_2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_24_2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201802242307518_02_24_2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
